---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neon
spec:
  replicas: 
  selector:
    matchLabels:
      app: neon
  template:
    metadata:
      labels:
        app: neon
    spec:
      containers:
      - name: neon
        image: noicecurse.jfrog.io/default-docker-local/noicecurse/neon:1
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: jfrog
---
apiVersion: v1
kind: Service
metadata:
  name: neon
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: neon